### ISSUE TITLE
unions may not contain fields that need dropping

### ISSUE THREAD

**Issue by gz** [edef1c/libfringe#82]
master fails to compile on latest rustc (rustc 1.40.0-nightly (b520af6fd 2019-11-03)):

```
error[E0740]: unions may not contain fields that need dropping
  --> src/generator.rs:95:3
   |
95 |   inner: T
   |   ^^^^^^^^
   |
```

**Comment by edef1c** [comment]
Fixed by 17c41ce777a8484213b024d9ac3b6395fa8b188c ^_^
